### ISSUE TITLE
HTTP Сonnection close causes WebClient freeze

### ISSUE THREAD

**Issue by alexmaddriver** [reactor/reactor-netty#163]
We use Netty based Web Flux WebClient as a transparent proxy in our backend and faced with several issues. They happen when HTTP connections are not reused (closed after each request).

First of all, WebClient freezes under the load, secondly it sometimes writes into closed connections (seen  in Wireshark dumps).

The problems are stably reproduced with the following setup:

5-10 client emulaters generating HTTP GET requests <-> WebClient proxy <-> Content serving backed

Content serving backend has one specifics - it doesn't support connection reuse and returns HTTP connection close for each GET request. With connection reuse the proxy works fine. However once connection close is enabled, the proxy freezes after 200-300 requests and time to time writes to already closed TCP channels, resulting in TCP RST (Reset flag) from the content backend.

The issue was reproduced with both stacks:
* Spring 5.0.0.M5, Netty 4.1.9, Reactor 3.0.7.RELEASE, Reactor-netty 0.6.5.RELEASE
* Spring 5.0.0.RC3, Netty 4.1.15, Reactor 3.1.0.M3, Reactor-netty 0.7.0.M1

**Comment by alexmaddriver** [comment]
Might be wrong as we are not that familiar with reactor-netty code, but seems neither WebClient nor HttpClientHandler handle HTTP connection close cases. If true, then it is most likely the reason of the above issues.

**Comment by alexmaddriver** [comment]
Investigating further shown that this case has similarities with https://github.com/reactor/reactor-netty/issues/138. 
Disabling connection pool for WebClient resolved hangs.

**Comment by violetagg** [comment]
Hello,

I committed a fix for #138.
Do you think you can try the current 0.7.0.BUILD-SNAPSHOT version?

Thanks,
Violeta

**Comment by alexmaddriver** [comment]
Sure, will try it today.

**Comment by alexmaddriver** [comment]
Hello Violeta,

We've tested with reactor-netty-0.7.0.BUILD-20170908.110508-127.jar. 

Sorry to say, but our problems remain. The client keeps handing. Also in Wireshark we keep observing that sometimes it attempts to write to already closed TCP connections.

Let us know if we can somehow help you to reproduce or with fixing.

--
Alex

**Comment by violetagg** [comment]
Are you able to extract some simple reproducible example? This will definitely speed up the investigation.

Thanks

**Comment by rstoyanchev** [comment]
> 5-10 client emulaters generating HTTP GET requests <-> WebClient proxy <-> Content serving backed

Perhaps a sample code snippet of the code you're using? Of if it is a Boot app, maybe you can put something together with start.spring.io.

**Comment by alexmaddriver** [comment]
Here is the code reproducing the issue: https://gist.github.com/alexmaddriver/dfd28aecf93032a24e57380066d27186

Start startContentServer, then startProxyServer, then startEmulatingClients.
Client emulator outputs progress and errors. In case "Connection: close" on the content server side is commented out, the client successfully completes. Otherwise hangs and reports a few errors.

**Comment by smaldini** [comment]
I translated the case into a reactor-netty one as in https://gist.github.com/smaldini/4064edc8eeb4cb32651968b120209943 and at least i can't reproduce with the latest tweaks today. I'll investigate more if you reproduce it.

**Comment by alexmaddriver** [comment]
The issue has gone with M2 update, no longer reproduced in our environments. Thank you so much for fast responses and the fix!
