### ISSUE TITLE
HTTP2 - Active Connections and Streams Leak when maxLifeTime is set for the ConnectionProvider

### ISSUE THREAD

**Issue by siavashta** [reactor/reactor-netty#1982]
The netty reactor does not shut down/reduce the active connections/streams when the max lifetime is reached. Hence, The active connections and active streams leak. Please note that the maxLifeTime and evictionInbackground are set. 
It looks like MaxLifeTime is not respected.

## Expected Behavior
1-  When there is no request, we should see the active streams and active connection go back to 0.
2- When there is a constant request, we should see valid # active connections and streams.

## Actual Behavior
1- When there is no constant request, we see that no effort has been made by netty to shut down the active connections and streams gracefully after the maxLifeTime is reached. They remain in a bad state (i.e active_connection: 17, active streams: 40)
2- When there is a constant request, we see that active connections and streams keep going up. Although the leak is more visible for active streams.

## Steps to Reproduce

1-  checkout `h2ConnAndStremLeak` branch from [sia-h2](https://github.com/siavashta/sia-h2) repo
```
git clone -b h2ConnAndStremLeak git@github.com:siavashta/sia-h2.git
```
2- run the server and client
```
siaserver % mvn spring-boot:run
siaclient % mvn spring-boot:run
```
3- open JMeter and send 200reqs/sec(Number of Threads) with 3 times (Loop Count)
```
stahmureszadeh@TOR-MBP-7724 sia-h2 % jmeter -t siaclient/client.jmx
```
please note that maxLifeTime is set to 20 secs and evictInBackground set 5 secs.
```
        var provider = ConnectionProvider.builder("sia")
                .fifo()
                .maxConnections(100)
                .maxLifeTime(Duration.ofSeconds(20))
                .evictInBackground(Duration.ofSeconds(5))
                .metrics(true)
                .build();
 
```
4- open prometheus metrics page after 2-3mins (http://localhost:9066/prometheus) or check the logs and look for `active_connections` and `active_streams`.
```
reactor_netty_connection_provider_active_streams{id="1624003311",name="http2.sia",remote_address="localhost:9192",} 131.0
reactor_netty_connection_provider_total_connections{id="1624003311",name="sia",remote_address="localhost:9192",} 26.0
```
**We expected maxLifetime to kick in and reset the ActiveConnections and ActiveStrems to 0, but they remained at the mentioned numbers without any sign of recovery**

if you keep the Jmeter sending the constant number of requests (set Loop count to infinite), you will see the active_connections, and specifically `active_streams` will constantly increase without any recovery.
i.e 200 reqs/sec should be handled by around 10 connections each accepting 20 streams (set by server).
Math: 
10 conns * 20 streams 200 reqs. 
So, we expect to handle 200req/sec with active conns around 10-20 and streams around 20-50 all the time, but active streams keep going up forever. after 30 mins we saw the active stream reached 150

**Comment by stahmureszadeh-r7** [comment]
any update?

**Comment by violetagg** [comment]
I'm gonna work on this one.

**Comment by violetagg** [comment]
@stahmureszadeh-r7 Your test example uses Spring Boot 2.5.4. We have a known issue that we fixed 2-3 months ago. I updated the example to Spring Boot 2.5.9 and I do not see any issues. Can you verify that you are using the latest Spring Boot 2.5.x version.

**Comment by rtonini-r7** [comment]
We upgraded the spring version to 2.5.9 but are still seeing strange metrics.  For example if we set loop count to infinite and number of threads to like 500 on jmeter we see the number of streams and number of active connections continuously increase.  I left it running for only about 5 min and active connections went from 50 to 110, similar for streams 540 to 658.  

We are using openjdk 11.0.11 and Mac OSX 10.15.7 (for local testing)

**Comment by violetagg** [comment]
@rtonini-r7 Here are the changes that I made to the provided example
https://github.com/violetagg/sia-h2/commit/525e4480116194d8616ed81a4e8a7ba5c5b02132

I have temurin-11.0.14, Mac OS, apache-jmeter-5.4.1

All the time while the test is running I'm seeing

http://localhost:8080/actuator/metrics/reactor.netty.connection.provider.active.connections

```
{"name":"reactor.netty.connection.provider.active.connections","description":"The number of the connections that have been successfully acquired and are in active use","baseUnit":null,"measurements":[{"statistic":"VALUE","value":100.0}],"availableTags":[{"tag":"name","values":["sia"]},{"tag":"remote.address","values":["localhost:9192"]},{"tag":"id","values":["1709294687"]}]}
```

http://localhost:8080/actuator/metrics/reactor.netty.connection.provider.active.streams

```
{"name":"reactor.netty.connection.provider.active.streams","description":"The number of the active HTTP/2 streams","baseUnit":null,"measurements":[{"statistic":"VALUE","value":100.0}],"availableTags":[{"tag":"name","values":["http2.sia"]},{"tag":"remote.address","values":["localhost:9192"]},{"tag":"id","values":["1709294687"]}]}
```

**Comment by violetagg** [comment]
> Meanwhile reactor.netty.connection.provider.active.connections shows about ~500 active connections which doesn't seem to make sense given we are using h2.

In the example the server limits the streams to 1 so there is one stream per connection at a time, so it behaves like http/1.1

https://github.com/violetagg/sia-h2/blob/525e4480116194d8616ed81a4e8a7ba5c5b02132/siaserver/src/main/java/com/example/siaserver/SiaserverApplication.java#L20

**Comment by rtonini-r7** [comment]
We were using the branch `h2ConnAndStremLeak` https://github.com/violetagg/sia-h2/blob/h2ConnAndStremLeak/siaserver/src/main/java/com/example/siaserver/SiaserverApplication.java which sets 20 as default h2 streams on server.

We see this on client side logs 
```
2022-01-31 17:06:30.236 DEBUG 81435 --- [tor-http-nio-12] r.n.http.client.Http2ConnectionProvider  : [2f1ccb21, L:/127.0.0.1:49215 - R:localhost/127.0.0.1:9192](H2 - 11) Stream closed, now: 1 active streams and 20 max active streams.
```

Also we still see active streams increase over time albiet slowly.  After a few minutes we saw the metric climb from 602 to 635 then few minutes later 750+.  
```
{"name":"reactor.netty.connection.provider.active.streams","description":"The number of the active HTTP/2 streams","baseUnit":null,"measurements":[{"statistic":"VALUE","value":795.0}],"availableTags":[{"tag":"name","values":["http2.sia"]},{"tag":"remote.address","values":["localhost:9192"]},{"tag":"id","values":["1194694683"]}]}
```

**Comment by violetagg** [comment]
@siavashta @rtonini-r7 Thanks for the example and the explanation of the use case! I was able to reproduce it and prepared a fix #2014

**Comment by violetagg** [comment]
@siavashta @rtonini-r7 The fix is available in 1.0.16-SNAPSHOT. If you are able to test it, it will be great.

**Comment by stahmureszadeh-r7** [comment]
> @siavashta @rtonini-r7 The fix is available in 1.0.16-SNAPSHOT. If you are able to test it, it will be great.

Thanks for the resolution. We will test it and let you guys know by end of the day tomorrow.

**Comment by rtonini-r7** [comment]
@violetagg from initial testing looks like the active streams are now stable!

But I notice the active connections are still incredibly sporadic.  When we reach higher load like when jmeter is set to 500 threads and infinite loops, can sometimes be really high like 400+ as though we weren't using h2c.  I wonder if this is because we set a low `maxLifeTime` at 20s?

**Comment by violetagg** [comment]
@rtonini-r7 What is the configuration for max connections 100 or 500?

**Comment by rtonini-r7** [comment]
I am using max connections 1000

**Comment by violetagg** [comment]
@rtonini-r7 Let me summarise the settings that you have (correct me if they are wrong)

- max connections 1000
- maxLifeTime 20s
- max streams 20

What happens:
1. At the beginning when you start the load test, you send **500** requests in **parallel**. (I don't know whether you have some ramp-up time or not)
2. The connection pool is empty. For **n** (up-to 500) of the initial parallel requests we will establish connections, because the pool allows that (max 1000 connections). (the pool is empty, we need to handle the incoming parallel requests, establishing a connection is time consuming and the pool will need some time in order to start caching the connections)
3. For the rest of the parallel requests we will start reusing the connections and creating streams on these connections.
4. Depending on how fast the response is received (here it matters whether you test everything on a local machine or over the network because network latency matters), at some point we will reach max streams and we will try to establish new connections if the pool allows that.
5. At some point of time the connections will reach **maxLifeTime**. In a scenario with one endpoint (constant response time) and testing on a local machine where you do not have network latency, the chance all connections in the pool to be closed because they reached their max life time at one and the same time is high and if that happens basically you will almost empty the connection pool and we will need to start establishing new connections again. (back to the point 1.)

**Comment by rtonini-r7** [comment]
Thanks for the clarification.  That makes sense.

**Comment by Shaphan** [comment]
Howdy! Is the issue only scoped to HTTP/2? Should I have any concerns about using max connection lifetime with HTTP/1.1 and versions of reactor-netty earlier than 1.0.16 in the light of this issue?

**Comment by violetagg** [comment]
@Shaphan This issue is related only yo HTTP/2

**Comment by Shaphan** [comment]
> @Shaphan This issue is related only to HTTP/2

Thanks for the confirmation!
