### ISSUE TITLE
/cloudfoundryapplication-Endpoints queried for port 80 instead of 443 after update from reactor-netty 1.0.28 to 1.0.30

### ISSUE THREAD

**Issue by boborperry** [reactor/reactor-netty#2771]
Initially I created this issue [here ](https://github.com/spring-projects/spring-boot/issues/34851) as the behaviour originated after updating from spring-boot 2.7.9 to 2.7.10 (raising reactor netty from 1.0.28 to 1.0.30). After some further research I think I might pin it down to the related reactor-netty update. 

Here is the behaviour:

We're running spring-boot-starter with spring-cloud-gateway 3.1.16 on cloud foundry platform. When updating from spring-boot-starter 2.7.9 to 2.7.10 the /cloudfoundryapplication-Endpoints (which are accessed by cloudfoundry-Apps-Manager for example by using Google Chrome) stop working.This means that using actuator endpoints like configuring loggers on the fly or viewing build info via spring-boot-maven-plugin) no longer work with cloudfoundry-Apps-Manager.

This behaviour seems to result from a bad ssl-handshake. By observing the network protocol in Chrome Browser the following seems to happen in version 2.7.10:

1. OPTIONS-Request to https://[host]/cloudfoundryapplication (port 443)

2. GET-Request to https://[host]/cloudfoundryapplication happens (port 443). The response body contains json with urls of actuator-endpoints. However, these endpoints contain port 80, example:

`{"_links":{"caches":{"href":"https://[host]/cloudfoundryapplication:80/loggers","templated":false},`

3. On subsequent requests of cloudfoundry-apps-manager to https://[host]:80/cloudfoundryapplication/info (or /loggers etc) no https-connection can be established (connection refused)

However, manual requests to https://[host]:443/cloudfoundryapplication/info return status code 200 and the expected result indicating that the acutator-endpoints are still configured properly

Until version 2.7.9 the request in 2) returned endpoints with no port (indicating using default https-port 443).
`{"_links":{"caches":{"href":"https://[host]/cloudfoundryapplication/loggers","templated":false},`

Checking the logs of a sample request reveals that only x_forwarded_proto and x_forwarded_for headers are present:

`2023-04-12T19:04:57.323+02:00   [2023-04-12T17:04:57.272549114Z] "GET /cloudfoundryapplication HTTP/1.1" 200 x_forwarded_for:"10.236.177.224, 10.236.177.224" x_forwarded_proto:"https" `

I may add that setting
```
server.forward-headers-strategy: none or
server.forward-headers-strategy: framework
```
restores the correct behaviour while
`server.forward-headers-strategy: native`

does not. However, native is the default setting in cloud foundry according to [Spring Docs ](https://docs.spring.io/spring-boot/docs/2.7.10/reference/htmlsingle/#howto.webserver.use-behind-a-proxy-server) and I cannot judge all effects especially in a gateway with the main purpose of routing. 

This issue might be related due to recent changes in DefaultHttpForwardedHeaderHandler by @violetagg but further analysis is beyond my skills. Thanks for checking. 

## Expected Behavior
Usage of port 443 instead of port 80 when x_forwarded_proto indicates usage of https (as before). 

## Actual Behavior
Usage of port 80.

## Steps to Reproduce
see above and initial [Spring Boot Issue](https://github.com/spring-projects/spring-boot/issues/34851) with sample application attached as zip. 

## Your Environment
* Reactor version(s) used: 1.0.28 vs 1.0.30
* JVM version (`java -version`): 11

**Comment by pderop** [comment]
Hi @boborperry ,

Can you give a try to the latest reactor-netty **1.0.31** version which has been released two days ago ?
In this version, we have fixed https://github.com/reactor/reactor-netty/pull/2761, which might be related to the issue, so let's first check if #2761 helps.

please let me know ?

**Comment by boborperry** [comment]
Hi @pderop,
thanks for getting in touch so quickly. Unfortunately, the problem persists after updating reactor-netty-core and reactor-netty-http to 1.0.31.

If I had to guess: The fix for #2761 takes into account the x-forwarded-**port** header which does not seem to be present in requests to /cloudfoundryapplication in contrast to x_forwarded_**proto** header.

**Comment by boborperry** [comment]
Thanks a lot for your efforts @pderop. Been after this issue for a while.

Yes, I did not come up with an idea for reproducing this issue locally so thanks for that too.

**Comment by pderop** [comment]
Hi @boborperry,

some updates: so I have attempted a candidate PR #2772, will you be able to give it a try ? I can't push it for the moment, because I need more review from other reactor-netty team members who are not available for the moment, however, if it's urgent for you then let me know.

So, I think what happened is the following: as you said, the problem starts from spring boot 2.7.10. In this version, the following change has been made in spring-web `ReactorServerHttpRequest` class, which now extracts the request `hostName` and **`hostPort`** from the ReactorServerHttpRequest.

see the [ReactorServerHttpRequest](https://github.com/spring-projects/spring-framework/commit/f0da099b127f0b281f15e3baff62a55fd0cd9355
) diff between 2.7.9 and 2.7.10. This change comes from [this GH issue](https://github.com/spring-projects/spring-framework/issues/29974).

So, this change is correct, but it now picks up the host port from the  **request**. Pay attention to the new `usePort` method, and line 85:

```
                 int port = request.hostPort();
		return scheme + "://" + request.hostName() + (usePort(scheme, port) ? ":" + port : "");
```

So, this seems correct, there is no problem here, but in reactor-netty, the point is that hostPort() returns 80 instead of 443, because we don't take into account the "X-Forwarded-Proto: https" header. Before, it was working because the host port was not retrieved from the request.
See attached debug screen shot with the old spring boot 2.7.9: we see that the generated  generated is correct and does not include the unexpected 80 port ("https://myproxy.com"), because no port was present in the Host header: 

![Screenshot 2023-04-14 at 11 52 19](https://user-images.githubusercontent.com/650758/232057600-8a0230b2-7b89-470f-aebe-80a2b5616c94.png)

thank you.

**Comment by boborperry** [comment]
Hi pderop,

thanks a lot for your response and again your efforts. As far as I can tell from your code changes this should fix my issue; I would love to try this out. However, due to company restrictions I am only allowed to use built artifacts from a repository and push them to our cloud foundry instance. 

For the time being we can stick with 2.7.9 so I would not consider this as urgent.

**Comment by pderop** [comment]
ok, then let's delay a bit this PR.
Do not hesitate to ping in case you suddenly need the patch to be pushed.

thanks !

**Comment by nmck257** [comment]
Hi - I'd vote for that patch to come soon, if it's cheap to do so :)

As far as I can tell, this issue is pervasive for Spring Boot apps using Webflux on the latest patch versions and running on CloudFoundry (with default settings); as you described earlier, apps can switch to `server.forward-headers-strategy: framework` as a workaround, but I expect that most relevant apps aren't setting that property at all since Spring is clever about defaulting you to `native` if running on CF.

I'm also in a walled environment and can't easily validate your PR, but your description of the issue exactly matches what I had found, so I expect that your fix is targeted appropriately.

**Comment by pderop** [comment]
all right, I will ask someone from the team to review the PR #2773 in order to be able to merge it asap.
thanks.

**Comment by pderop** [comment]
@rstoyanchev , 

Can you take a look and review the #2773 PR which might resolve this issue ? or maybe you think about something else to do ? I have summarize the issue which I suspect in the #2773, please check.

You can also run the attached [reproducer.tgz](https://github.com/reactor/reactor-netty/files/11236215/reproducer.tgz) like this:

run the sample app:
```
./gradlew bootRun
```

then from a console, send the curl command which simulates a request that is sent by a front-end proxy that is providing a Host header , as well as only a `X-Forwarded-Proto: https` header:

```
curl  -v -H "Host: myproxy.com" -H "X-Forwarded-Proto: https" http://localhost:8080/actuator
```

you will get the following bad json response, with the unexpected appender port 80:

```
{"_links":{"self":{"href":"https://myproxy.com:80/actuator","templated":false},"health":{"href":"https://myproxy.com:80/actuator/health","templated":false},"health-path":{"href":"https://myproxy.com:80/actuator/health/{*path}","templated":true}}}[pderopJ2WQL demo] 
```

Next, you can build the reactor-netty from #2773, and deploy it to your local M2 (using  `./gradlew publishToMavenLocal`), then you can then update the reproducer build.gradle and uncomment the two commented dependences for reactor-netty 1.0.32-SNAPSHOT:

```
dependencies {
	implementation 'io.projectreactor.netty:reactor-netty-core:1.0.32-SNAPSHOT'
	implementation 'io.projectreactor.netty:reactor-netty-http:1.0.32-SNAPSHOT'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'io.projectreactor:reactor-test'
}
```

Then restart the reproducer, and redo the same curl command, this time, you will get the following json response without the unexpected 80 port:

```
{"_links":{"self":{"href":"https://myproxy.com/actuator","templated":false},"health-path":{"href":"https://myproxy.com/actuator/health/{*path}","templated":true},"health":{"href":"https://myproxy.com/actuator/health","templated":false}}}[pderopJ2WQL demo] 
```

thanks !

**Comment by pderop** [comment]
Hi @boborperry ,

I have few more questions; when you have the problem:

- can you confirm that the front end cloundfoundry is forwarding the request to the application in **non-secure** http ?
- If so, can you provide a wireshark trace of the http request that is received by the application ? I'd like to check all the http request headers that are present in the http request. I think that only the **Host** and **X-Forwarded-Proto** headers are present, but I'd like to be 100% sure about that.
- if the application is received in secure mode, can you manage to log all the headers of the received request ?

thanks a lot

**Comment by boborperry** [comment]
Hi @pderop,

just to clarify, as far as I can tell forwarding is done by some kind of cloudfoundry load balancer, not the frontend itself. 

Concerning your questions: I would say it actually seems like the request is forwarded to a https-connection. Here's a log of all headers except authorization:

```
Method: GET                                                                                                                                            
URI: /cloudfoundryapplication                                                                                                                          
Protocol: HTTP/1.1                                                                                                                                     
URL: https://[app-server-no-port-given]/cloudfoundryapplication                                                                                                      
Header-key: host / Header-Value [app-server]                                                                                                           
Header-key: user-agent / Header-Value Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36  
Header-key: accept / Header-Value */*                                                                                                                  
Header-key: accept-encoding / Header-Value gzip, deflate, br                                                                                           
Header-key: accept-language / Header-Value de                                                                                                          
Header-key: b3 / Header-Value 5ee2fcd44ec7de604d2be7d9b6881a07-4d2be7d9b6881a07                                                                        
Header-key: origin / Header-Value [frontend-server-cloud-foundry]                                                                                      
Header-key: sec-ch-ua / Header-Value "Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"                                                 
Header-key: sec-ch-ua-mobile / Header-Value ?0                                                                                                         
Header-key: sec-ch-ua-platform / Header-Value "Windows"                                                                                                
Header-key: sec-fetch-dest / Header-Value empty                                                                                                        
Header-key: sec-fetch-mode / Header-Value cors                                                                                                         
Header-key: sec-fetch-site / Header-Value same-site                                                                                                    
Header-key: x-b3-spanid / Header-Value 4d2be7d9b6881a07                                                                                                
Header-key: x-b3-traceid / Header-Value 5ee2fcd44ec7de604d2be7d9b6881a07                                                                               
Header-key: x-cf-applicationid / Header-Value 7f688bd6-eaaf-484e-9a84-cca2d3725168                                                                     
Header-key: x-cf-instanceid / Header-Value 015fddac-ae95-4e63-7c78-0299                                                                                
Header-key: x-cf-instanceindex / Header-Value 0                                                                                                        
Header-key: x-forwarded-proto / Header-Value https                                                                                                     
Header-key: x-request-start / Header-Value 1681727941470                                                                                                                                          
```

**Comment by pderop** [comment]
Thanks for the logs.

> Concerning your questions: I would say it actually seems like the request is forwarded to a https-connection. Here's a log of all headers except authorization:

But In the [reproducer code](https://github.com/spring-projects/spring-boot/files/11155502/cloudfoundry-sample.zip), the application endpoint which receives the /actuator request is listening on 8080 port. based on the reproducer, I was thinking that the cloudfoundry load balancer was forwarding the **https** request to the destination application in **http** (non secure mode, like in the reproducer code, on port 8080) ? Let me clarify: the pending PR is fixing the issue only when :
- the load balancer forwards the original **https** request to the target application using **http** (non-secure port 8080 in the original reproducer)
- when the request forwarded by the load balancer contains a Host header without a port
- when the forwarded request contains a `x-forwarded-proto: https`header (without any x-forwarded-host header)
- and when the target applications is configured with `forward-headers-strategy=native`

can you please double check ?

Now, if the PR is really fixing the issue, it turns out that we will only be able to merge it the next early week and the patch will be only available from the repo.spring.io **SNAPSHOT** repository. The next official RELEASE will be done the second week of the next month (in May). Please confirm that you are OK with this plan ? (doing an official 
 release is not cheap).
 
thanks for your patience, let me know ?

**Comment by boborperry** [comment]
@pderop 
Thanks for coming back on this. I double checked and it is **https** indeed.

Although I have to admit that the logging above results from the reproducer which was still switched to spring web mvc. I repeated with the reproducer, webflux and spring boot 2.7.9 / 2.7.10 - results are almost the same except for an additional X-Forwared-For in both versions and port 80 with 2.7.10. See below for details.

My apologies for any confusion done.

2.7.9
```
Method: GET
URI: https://[app-server-no-port-given]/cloudfoundryapplication
LocalAddress: /10.16.6.171:8080
Header-key: Host / Header-Value [app-server-no-port-given]
Header-key: User-Agent / Header-Value [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36]
Header-key: Accept / Header-Value [*/*]
Header-key: Accept-Encoding / Header-Value [gzip, deflate, br]
Header-key: Accept-Language / Header-Value [de]
Header-key: B3 / Header-Value [4f0222f63887089860c47f4079d3cfef-60c47f4079d3cfef]
Header-key: Cache-Control / Header-Value [no-cache]
Header-key: Origin / Header-Value [frontend-server-cloud-foundry]
Header-key: Pragma / Header-Value [no-cache]
Header-key: Sec-Ch-Ua / Header-Value ["Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"]
Header-key: Sec-Ch-Ua-Mobile / Header-Value [?0]
Header-key: Sec-Ch-Ua-Platform / Header-Value ["Windows"]
Header-key: Sec-Fetch-Dest / Header-Value [empty]
Header-key: Sec-Fetch-Mode / Header-Value [cors]
Header-key: Sec-Fetch-Site / Header-Value [same-site]
Header-key: X-B3-Spanid / Header-Value [60c47f4079d3cfef]
Header-key: X-B3-Traceid / Header-Value [4f0222f63887089860c47f4079d3cfef]
Header-key: X-Cf-Applicationid / Header-Value [7f688bd6-eaaf-484e-9a84-cca2d3725168]
Header-key: X-Cf-Instanceid / Header-Value [23fd6fc3-0fbe-4bcd-5362-4dc0]
Header-key: X-Cf-Instanceindex / Header-Value [0]
Header-key: X-Forwarded-For / Header-Value [10.236.177.224, 10.236.177.224]
Header-key: X-Forwarded-Proto / Header-Value [https]
Header-key: X-Request-Start / Header-Value [1681739787213]
Header-key: X-Vcap-Request-Id / Header-Value [3b34b5eb-f221-4abd-64bf-6232a2de250c]         
```

2.7.10
```
Method: GET
URI: https://[app-server]:80/cloudfoundryapplication
LocalAddress: /10.18.93.91:8080
Header-key: Host / Header-Value [app-server]
Header-key: User-Agent / Header-Value [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36]
Header-key: Accept / Header-Value [*/*]
Header-key: Accept-Encoding / Header-Value [gzip, deflate, br]
Header-key: Accept-Language / Header-Value [de]
Header-key: B3 / Header-Value [27274336efd081991d10c5d87afae665-1d10c5d87afae665]
Header-key: Cache-Control / Header-Value [no-cache]
Header-key: Origin / Header-Value [frontend-server-cloud-foundry] 
Header-key: Pragma / Header-Value [no-cache]
Header-key: Sec-Ch-Ua / Header-Value ["Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"]
Header-key: Sec-Ch-Ua-Mobile / Header-Value [?0]
Header-key: Sec-Ch-Ua-Platform / Header-Value ["Windows"]
Header-key: Sec-Fetch-Dest / Header-Value [empty]
Header-key: Sec-Fetch-Mode / Header-Value [cors]
Header-key: Sec-Fetch-Site / Header-Value [same-site]
Header-key: X-B3-Spanid / Header-Value [1d10c5d87afae665]
Header-key: X-B3-Traceid / Header-Value [27274336efd081991d10c5d87afae665]
Header-key: X-Cf-Applicationid / Header-Value [7f688bd6-eaaf-484e-9a84-cca2d3725168]
Header-key: X-Cf-Instanceid / Header-Value [2d74c579-113d-4775-539d-3944]
Header-key: X-Cf-Instanceindex / Header-Value [0]
Header-key: X-Forwarded-For / Header-Value [10.236.177.224, 10.236.177.224]
Header-key: X-Forwarded-Proto / Header-Value [https]
Header-key: X-Request-Start / Header-Value [1681740099835]
Header-key: X-Vcap-Request-Id / Header-Value [8ce257e2-bef8-4d49-7744-5a473ee7e08c]   
```

**Comment by nmck257** [comment]
> Now, if the PR is really fixing the issue, it turns out that we will only be able to merge it the next early week and the patch will be only available from the repo.spring.io **SNAPSHOT** repository. The next official **RELEASE** will be done the second week of the next month (in May). Please confirm that you are OK with this plan ? (doing an official
> release is not cheap).

That seems reasonable to me; thank you!

**Comment by boborperry** [comment]
@pderop,

I could not check back with our internal cloud foundry operators on the exact configuration. However, I added logging of **getSslInfo()** which returns null and verifies your thesis.

**Comment by pderop** [comment]
thanks @boborperry for having checked that.
:+1:

**Comment by svankamamidi** [comment]
We are also facing this issue and could not upgrade.

**Comment by sven-tsi** [comment]
We ware also facing this issue with Spring Boot 2.7.10 and Spring Boot 3.0.6 in the https oauth redirect uri which now contains the port 80.

**Comment by violetagg** [comment]
Hi All,

The fix will be included in the next Reactor Netty release.
Current planning for the next release is May 9th.

**Comment by svankamamidi** [comment]
@pderop using config forward-headers-strategy: framework
ServerWebExchange exchange
exchange.getRequest().getURI().getPort() is returning 80 when an https end point is invoked.

**Comment by pderop** [comment]
@svankamamidi ,

ok, I will check this.

**Comment by pderop** [comment]
Hi @svankamamidi ,

I have updated the [reproducer](https://github.com/spring-projects/spring-boot/files/11155502/cloudfoundry-sample.zip) and applied your instructions:

- I'm using forward-headers-strategy: framework
- I have tested with 2.7.9, 2.7.10, 2.7.11-SNAPSHOT 
- I have tested with 2.7.10 with the patch
- I tested using this curl: 

curl -v -H "Host: cloudfoundryapplication"  -H "X-Forwarded-Proto: https" http://localhost:8080/print-uri

and here is the sample rest endoint:

@RestController
public class PrintUriController {

    @GetMapping(value = "/print-uri", produces = MediaType.APPLICATION_JSON_VALUE)
    public Mono<String> printUri(ServerWebExchange exchange) throws URISyntaxException {
        System.out.println("XX: URI=" + exchange.getRequest().getURI());
        System.out.println("XX: port=" + exchange.getRequest().getURI().getPort());
        return Mono.just(exchange.getRequest().getURI()).map(URI::toString);
    }
}

but in any cases, I cannot reproduce the issue:

- exchange.getRequest().getURI() returns `https://cloudfoundryapplication/print-uri`
- exchange.getRequest().getURI().getPort() returns -1 (which seems correct regarding the documentation of the java.net.URI: getPort() returns the port component of this URI, or -1 if the port is undefined in the URI. 

 
maybe my scenario is not correct ? can you tell me how to reproduce ?

**Comment by svankamamidi** [comment]
@pderop I am using via Spring Gateway, may be that is the difference between your setup and mine.

**Comment by pderop** [comment]
can you provide the wireshark of the http request received by the backend application, I'd like to check the http headers that are sent by the spring cloud gateway ? if you can't provide the wireshark, at least , I need the list of http request headers.

thanks.

**Comment by pderop** [comment]
@svankamamidi ,

actually, please open a new issue for the exchange.getRequest().getURI().getPort() problem, and then attach to it the informations that I asked in my previous message. a PR is about to be merged for this current issue, so maybe you will be able to test it, in case it resolves the getPort() issue ?

thanks.

**Comment by pderop** [comment]
Closing this issue as completed in 8eefda0649b29f68fbeec10b81e2025aab908dde.

**Comment by svankamamidi** [comment]
@pderop created this new issue https://github.com/reactor/reactor-netty/issues/2788

**Comment by pderop** [comment]
@boborperry ,

in case you are able to validate, just to say that the fix for this issue is available from the https://repo.spring.io/ snapshot repository (reactor-netty 1.0.32-SNAPSHOT).

thanks.

**Comment by boborperry** [comment]
@pderop 
I was able to do a quick check with my reproducer app, our productive app, SB 2.7.10 and including reactor-netty-core as well as reactor-netty-http in version 1.0.32-SNAPSHOT.

I can confirm that /cloudfoundryapplication-endpoints are queried correctly now.

Thank you and also @violetagg for fixing this issue.

**Comment by abelsromero** [comment]
I can confirm too, we have been able to solve the issue with the netty 1.0.32-SNAPSHOT and reactor-core 3.4.30-SNAPSHOT for Spring Cloud Gateway.

**Comment by svankamamidi** [comment]
I can confirm that 'io.projectreactor.netty:reactor-netty-core:1.0.32-SNAPSHOT'
 and 'io.projectreactor.netty:reactor-netty-http:1.0.32-SNAPSHOT' resolved our issue. Where as setting server.forward-headers-strategy: framework did not addressed all scenario's. Especially ServerWebExchange.getRequest().getURI().getPort() is returning 80 when an https end point is invoked.
